### ISSUE TITLE
Make real test dataset available

### ISSUE THREAD

**Issue by martinaryee** [aryeelab/guideseq#11]
e.g. from guideseq paper

**Comment by vedtopkar** [comment]
Thoughts on where we should do this?

**Comment by vedtopkar** [comment]
@martinaryee @shengdar perhaps we can serve this from the casper server? We should check on how much bandwidth we are allowed, however.

**Comment by martinaryee** [comment]
I put it up here a little while back but haven't tested it yet:
http://aryee.mgh.harvard.edu/guideseq/data/guideseq_test_fastq.zip

**Comment by vedtopkar** [comment]
Awesome! @shengdar do you mind testing the dataset on the cluster? We can add it to the readme once this is confirmed to work.

**Comment by martinaryee** [comment]
We also need to add the yaml manifest for this run.

**Comment by martinaryee** [comment]
The 4 undemultiplexed FASTQs (R1, R2, I1, I2) from run 131007_M01326_0075_000000000-A6B33 and the yaml manifest are available here: http://aryee.mgh.harvard.edu/guideseq/data/guideseq_test_fastq.zip

**Comment by JoeEmendo** [comment]
The link no longer works, can you provide the data again? Thanks!
