### ISSUE TITLE
Test dataset for guideseq package

### ISSUE THREAD

**Issue by shengdar** [aryeelab/guideseq#16]
Add the small truncated dataset to the repository for quick guideseq functionality testing.

**Comment by shengdar** [comment]
There is currently no test dataset in the guideseq repository, and the dataset in the umi directory is not compatible with the full workflow.

**Comment by vedtopkar** [comment]
fixed, see dev branch for new testing features. major thanks to @martinaryee for generating a clever way to test the alignment step much faster with a truncated genome.

**Comment by martinaryee** [comment]
Great! What do you think is the best way to run the local test? Should tox compile the bwa and bedtools dependencies?
