### ISSUE TITLE
Add ReverseComplementIndexRead2 option

### ISSUE THREAD

**Issue by shengdar** [aryeelab/guideseq#21]
Add ReverseComplementIndexRead2 option to YAML and pipeline to support NextSeq data.

One possible implementation would be to simply write out a reverse complemented index read2 at the demultiplexing stage. After that point, the remainder of the pipeline could run without additional modifications.

**Comment by martinaryee** [comment]
This should probably be implemented in the [umi](https://github.com/aryeelab/umi/wiki) package.

**Comment by vedtopkar** [comment]
Moved to Issue https://github.com/aryeelab/guideseq/issues/21 in the UMI package
