### ISSUE TITLE
Error in pip install -r requirements.txt

### ISSUE THREAD

**Issue by robyn-ball** [aryeelab/guideseq#33]
Fixed:
I was able to complete it by using

> sudo pip install -r requirements.txt

Original:
I'm getting a permissions error when I try to install all the dependencies. I have downloaded and installed Python 2.7, bwa, bedtools, and pip. I tried changing the permissions for this folder with chmod -R but was unable to do so. 

Below is the error. Any help is greatly appreciated.

q/_StepVector.so
    running build_scripts
    creating build/scripts-2.7
    copying and adjusting scripts/htseq-qa -> build/scripts-2.7
    copying and adjusting scripts/htseq-count -> build/scripts-2.7
    changing mode of build/scripts-2.7/htseq-qa from 644 to 755
    changing mode of build/scripts-2.7/htseq-count from 644 to 755
    running install_lib
    creating /Library/Python/2.7/site-packages/HTSeq
    error: could not create '/Library/Python/2.7/site-packages/HTSeq': Permission denied
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/_6/jzln984x4x52zfrzq4rxw3jc0000gn/T/pip-build-1KKOsn/HTSeq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/_6/jzln984x4x52zfrzq4rxw3jc0000gn/T/pip-lM1aws-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/_6/jzln984x4x52zfrzq4rxw3jc0000gn/T/pip-build-1KKOsn/HTSeq/

**Comment by vedtopkar** [comment]
Hi Robyn,

Glad to hear that you got it working!

Best,
Ved

**Comment by robyn-ball** [comment]
Thanks for getting back to me!
