### ISSUE TITLE
Umi module

### ISSUE THREAD

**Issue by michael-weinstein** [aryeelab/guideseq#35]
I'm having installation issues with the umi module.  Do you have a link for the package that should be installed, since it appears to have not installed itself during the install process?

Mike

**Comment by vedtopkar** [comment]
Hi Mike,

Are you using the following command when cloning the repository?

`git clone --recursive https://github.com/aryeelab/guideseq.git`

The `--recursive` flag makes sure that all sub-repos, like umi, are also cloned.

Ved

**Comment by michael-weinstein** [comment]
Thanks, I must have missed the recursive argument the first time.  Clean/reinstall took care of it!

**Comment by vedtopkar** [comment]
Glad to hear it!
