### ISSUE TITLE
Links in large_test.sh are "dead"

### ISSUE THREAD

**Issue by JoeEmendo** [aryeelab/guideseq#53]
The below link from the "large_test.sh" is no longer working, is it possible to re-activate or provide a new link for those of us who'd like to test the large dataset? Thanks!

wget http://aryee.mgh.harvard.edu/guideseq/data/guideseq_test_fastq.zip

EDIT:

A temporary work-around for anyone following this thread is to download from the SRR dataset. I believe you can get this with the below cmd, if you have NCBI CLI tools installed. Although these are only the read fastq files and not the indexes...

fastq-dump SRR1695633 -split-files -O /OUTPUT/DIRECTORY

**Comment by martinaryee** [comment]
Thanks for reporting this. We'll get the link fixed and back up. I'll post an update here.

**Comment by JoeEmendo** [comment]
Sorry to be annoying, but any update on this? Thanks.

**Comment by poppn** [comment]
Again, commenting looking for an update. Thanks.

**Comment by martinaryee** [comment]
We're having trouble getting the web server (and the test data it hosts) back up. We're going to regenerate the dataset. Thanks for your patience and sorry for the hassle!

**Comment by JoeEmendo** [comment]
Thanks. Here is what I get after unzip. Perhaps unnecessary, but can you include md5?
```
total 5.3G
-rw-rw---- 1 joe users 120M Oct 14  2015 Undetermined_S0_L001_I1_001.fastq.gz
-rw-rw---- 1 joe users 221M Oct 14  2015 Undetermined_S0_L001_I2_001.fastq.gz
-rw-rw---- 1 joe users 1.1G Oct 14  2015 Undetermined_S0_L001_R1_001.fastq.gz
-rw-rw---- 1 joe users 1.3G Oct 14  2015 Undetermined_S0_L001_R2_001.fastq.gz
-rw-r----- 1 joe users 1.1K Nov 17  2015 test_manifest.yaml
```

**Comment by JoeEmendo** [comment]
I did a fresh git clone and used the command `python ~/guideseq.py all -m ~/manifest.yaml` and received the below error.
```Traceback (most recent call last):
  File "~/guideseq.py", line 22, in <module>
    from umi import demultiplex, umitag, consolidate
ImportError: No module named umi```

**Comment by martinaryee** [comment]
I'm closing this issue. Please let us know if anyone is still having trouble.
